name: integratedbiologics
favicon: null
layout_spectrum: 0.5664854294154793
typography_spectrum: 0.47081574075855315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2679231222718954
  lightness: 0.7204854949377477
  saturation: 0.3005393303465098
  rhythmicContrast: 0.9154874663800001
purpose: []
